#### ####  See https://pre-commit.com for more information
#### ####  See https://pre-commit.com/hooks.html for more hooks
exclude: '.md$'
repos:
-   repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [               '--fail-under=7.5',
                '-rn', # Only message dysplay
                '-sn', # Don't display the score
                '--rcfile=.pylintrc', # Link to your config file
                '--load-plugins=pylint.extensions.docparams' #load an extension
                ]